// front/src/components/question.vue
<template>
    <div id='ques' style="width: 100%;">
      <div class="question">
        <h2>What is your purpose?</h2>
        <div class="checkboxes alignment" data-toggle="buttons-radio">
          <div class="checkbox">
            <input class="btn btn-info" type="checkbox" value="3DPrinter" v-model="checkedUse">
            <label for="3DPrinter" style="font-size: 20px">3DPrinter</label>
          </div>
          <div class="checkbox">
            <input class="btn btn-info" type="checkbox" value="LaserCutter" v-model="checkedUse">
            <label for="LaserCutter" style="font-size: 20px">LaserCutter</label>
          </div>
          <div class="checkbox">
            <input class="btn btn-info" type="checkbox" value="Training session" v-model="checkedUse">
            <label for="Training" style="font-size: 20px">Training</label>
          </div>
          <div class="checkbox">
            <input class="btn btn-info" type="checkbox" value="Other" v-model="checkedUse">
            <label for="Other" style="font-size: 20px">Other</label>
          </div>
        </div>
        <h3>If you have any request please fill in.</h3>
        <br>
        <textarea v-model="message" placeholder="" @keyup.ctrl.enter="send"></textarea>
        <br>
        <button ref="sendbtn" class="btn btn-info" v-on:click="send">send</button>
        <br>
        <h5>You can also use Control+Enter to submit your request.</h5>
      </div>
    </div>
</template>

<script>
import util from '../util.js'

export default {
  name: 'ques',
  data () {
    return {
      checkedUse: [],
      message: '',
      sending: false
    }
  },
  mounted: function () {
    if (!util.isShowQuestion()) {
      var userinfo = this.$route.params.userinfo
      util.addLog(userinfo['SID'], false, '')
      this.$router.push({ name: 'goodbye' })
    }
  },
  methods: {
    send: function () {
      if (this.sending) {
        return
      }
      this.sending = true
      this.$refs.sendbtn.disabled = true
      var userinfo = this.$route.params.userinfo
      var answer = JSON.stringify({
        'Use': this.checkedUse,
        'message': this.message
      })
      if (userinfo === undefined) {
        this.$router.push({ name: 'top' })
        return
      }
      util.addLog(userinfo['SID'], false, answer)
      this.$router.push({ name: 'goodbye' })
    }
  }
}
</script>

<style scoped>
h1, h2 {
  font-size: 60px;
  width: 100%;
  font-weight: normal;
}
input {
  font-size: 26px;
}
.checkbox input {
  width: 50px;
  height:50px;
}
.checkbox {
  display: flex;
  flex-flow: column nowrap;
  justify-content: center;
  align-items: center;
}
.checkboxes {
  width: 500px;
  height: 200px;
  display: flex;
  justify-content: center;
  align-items: center;
}
div .question textarea{
  resize: none;
  width:500px;
  height:200px;
}
div .question {
  width: 100%;
  display: flex;
  flex-flow: column nowrap;
  justify-content: center;
  align-items: center;
}
</style>

// front/src/components/Question.tsx
import { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { addLog, isShowQuestion } from '../utils/api';
import type { UserInfo } from '../types';
import styles from './Question.module.css';

function Question() {
  const [checkedUse, setCheckedUse] = useState<string[]>([]);
  const [message, setMessage] = useState('');
  const [sending, setSending] = useState(false);
  const sendBtnRef = useRef<HTMLButtonElement>(null);
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    if (!isShowQuestion()) {
      const userinfo = location.state?.userinfo as UserInfo | undefined;
      if (userinfo) {
        addLog(userinfo.SID, false, '');
      }
      navigate('/goodbye');
    }
  }, [location.state, navigate]);

  const handleCheckboxChange = (value: string) => {
    if (checkedUse.includes(value)) {
      setCheckedUse(checkedUse.filter((item) => item !== value));
    } else {
      setCheckedUse([...checkedUse, value]);
    }
  };

  const handleSend = () => {
    if (sending) {
      return;
    }

    setSending(true);
    if (sendBtnRef.current) {
      sendBtnRef.current.disabled = true;
    }

    const userinfo = location.state?.userinfo as UserInfo | undefined;
    const answer = JSON.stringify({
      Use: checkedUse,
      message: message,
    });

    if (!userinfo) {
      navigate('/');
      return;
    }

    addLog(userinfo.SID, false, answer);
    navigate('/goodbye');
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.ctrlKey && e.key === 'Enter') {
      handleSend();
    }
  };

  return (
    <div className={styles.ques}>
      <div className={styles.question}>
        <h2>What is your purpose?</h2>
        <div className={styles.checkboxes}>
          {['3DPrinter', 'LaserCutter', 'Training session', 'Other'].map((item) => (
            <div key={item} className={styles.checkbox}>
              <input
                type="checkbox"
                value={item}
                checked={checkedUse.includes(item)}
                onChange={() => handleCheckboxChange(item)}
              />
              <label style={{ fontSize: '18px' }}>
                {item === 'Training session' ? 'Training' : item}
              </label>
            </div>
          ))}
        </div>
        <h3>If you have any request, please fill in.</h3>
        <br />
        <textarea
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder=""
        />
        <br />
        <button ref={sendBtnRef} className="btn btn-info" onClick={handleSend}>
          send
        </button>
        <br />
        <h5 style={{ color: '#aaaaaa' }}>
          <span style={{ color: '#88aace' }}>Ctrl + Enter</span> to submit your request.
        </h5>
      </div>
    </div>
  );
}

export default Question;
